import tslint from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import globals from 'globals';

export default [
  'eslint:recommended',
  {
    languageOptions: {
      parserOptions: {
        ecmaVersion: 'latest',
      },
      parser: tsParser,
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    plugins: { '@typescript-eslint': tslint },
    rules: {
      indent: [
        'error',
        2,
        { SwitchCase: 1, ignoredNodes: ['TemplateLiteral > *'] },
      ],
      'linebreak-style': ['error', 'windows'],
      quotes: ['error', 'single'],
      semi: ['error', 'always'],
      'no-unused-vars': 'error',
      'no-constant-binary-expression': 'error',
      'no-constructor-return': 'error',
      'no-duplicate-imports': 'error',
      'no-promise-executor-return': 'error',
      'no-self-compare': 'error',
      'no-unreachable-loop': 'error',
      'no-unused-private-class-members': 'error',
      'no-use-before-define': 'error',
      'require-atomic-updates': 'error',
      'arrow-body-style': ['error', 'as-needed'],
      'block-scoped-var': 'error',
      camelcase: 'error',
      complexity: ['error', 10],
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-notation': 'error',
      eqeqeq: 'error',
      'grouped-accessor-pairs': 'error',
      'logical-assignment-operators': 'error',
      'max-depth': ['error', 4],
      'max-lines': ['error', 500],
      'max-lines-per-function': 'error',
      'max-nested-callbacks': ['error', 3],
      'max-params': ['error', 4],
      'max-statements': 'error',
      'new-cap': ['error', { capIsNew: false }],
      'no-array-constructor': 'error',
      'no-caller': 'error',
      'no-continue': 'error',
      'no-delete-var': 'error',
      'no-else-return': 'error',
      'no-empty-function': 'error',
      'no-empty-static-block': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-floating-decimal': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
    },
    files: ['**/*.ts', '**/*.js', '**/*.cjs', '**/*.mjs'],
  },
  {
    ignores: ['_site/**'],
  },
];
