[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/posts/2021-02-28-11ty-and-rollup"
  to = "/blog/2021-02-28-11ty-and-rollup"

[[redirects]]
  from = "/posts/2021-02-28-11ty-and-rollup/"
  to = "/blog/2021-02-28-11ty-and-rollup/"

[[redirects]]
  from = "/webdev-sins/button-as-link/"
  to = "/webdev-sins/2022-01-05-button-as-link/"

[[redirects]]
  from = "/webdev-sins/button-as-link/"
  to = "/webdev-sins/2022-01-05-button-as-link/"

[[redirects]]
  from = "/webdev-sins/render-static-content-on-the-client/"
  to = "/webdev-sins/2022-01-26-render-static-content-on-the-client/"

[[redirects]]
  from = "/webdev-sins/vdom-is-faster/"
  to = "/webdev-sins/2022-01-26-vdom-is-faster/"

[[redirects]]
  from = "/webdev-sins/vw-font-size/"
  to = "/webdev-sins/2022-02-07-vw-font-size/"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
  paths = [
    "_site/img", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]

  [plugins.inputs.thresholds]
    performance = 0.95
    accessibility = 1
    best-practices = 1
    seo = 1
    pwa = 1

  [[plugins.inputs.audits]]
    path = "/"

  [[plugins.inputs.audits]]
    path = "blog/"

  [[plugins.inputs.audits]]
    path = "blog/2022-07-29-starter-packs/"
