site_name: Snapstromegon's Blog (Raphael Höser)
site_short_name: "Snapstromegon:Blog"
description: "This is the blog of Snapstromegon (Raphael Höser) where I chat about web technologies and web development."
domain: hoeser.dev
theme_color: "#222"
subtitle: All thoughts are HTTP 203
url: https://www.hoeser.dev
feedUrl: https://www.hoeser.dev/feed.xml
favicon: assets/img/hummingbird_flipped.svg
author:
  name: Raphael Höser
  email: raphael@hoeser.info
  username: Snapstromegon
